Проверка рабочего процесса
htmlacademy-javascript/1471761-kekstagram-28 pull request #1
Opened 2023-03-01 20:49 UTC by LuizaLehu

---
:mortar_board: [Проверка рабочего процесса](https://up.htmlacademy.ru/javascript/28/user/1471761/tasks/6)

:boom: https://htmlacademy-javascript.github.io/1471761-kekstagram-28/1/

2023-03-02 10:10 UTC, KrapivinAV requested changes
Привет. Отмени, пожалуйста, изменения во всех файлах кроме readme.md

2023-03-02 10:10 UTC, KrapivinAV commented on package.json
> +    "browser-sync": "^2.28.1",
Зачем изменила версию пакета? И есть еще момент связанный с критерием https://up.htmlacademy.ru/javascript/28/criteries#b13
Лучше не трогай пока package.json

2023-03-02 13:27 UTC, LuizaLehu commented on package.json
> +    "browser-sync": "^2.28.1",
Здравствуйте Александр! Отменила изменения во всех файлах кроме readme.md. Случаино сделала изменения. Спасибо!

2023-03-04 06:37 UTC, KrapivinAV approved these changes

2023-03-04 06:38 UTC, merged